# Settings of jupyterhub


# https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html
proxy:
  secretToken: "<RANDOM_HEX>"
singleuser:
  # https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html
  image:
    name: pupster90/io
    tag: latest
  # https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html
  lifecycleHooks:
    postStart:
      exec:
        command: ["sh","-c","rm -rf welcome_to_lab && git clone https://github.com/anvit121/welcome_to_lab.git"]
  # https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html
  
# https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: true

